// <auto-generated />
using GourmetPizza.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace GourmetPizza.Migrations
{
    [DbContext(typeof(GourmetPizzaContext))]
    partial class GourmetPizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("GourmetPizza.Models.Pizza", b =>
                {
                    b.Property<int>("PizzaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PizzaName");

                    b.Property<decimal>("Price");

                    b.HasKey("PizzaID");

                    b.ToTable("Pizza");
                });
#pragma warning restore 612, 618
        }
    }
}
